### ISSUE TITLE
ERROR in ServiceWorkerPlugin: the `entry` option is incorrect.

### ISSUE THREAD

**Issue by praveen4554** [oliviertassinari/serviceworker-webpack-plugin#49]
i am using service worker plugin in my web pack project, getting error as  
ERROR in ServiceWorkerPlugin: the `entry` option is incorrect.
Child serviceworker-plugin:
   
    ERROR in ./src/sw.js
    Module parse failed: /Users/praveenkumar/Downloads/git/sunmool.client/src/sw.js Unexpected token (5:0)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (5:0)
        at Parser.pp$4.raise (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
        at Parser.pp.unexpected (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
        at Parser.pp$3.parseExprAtom (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
        at Parser.pp$3.parseExprSubscripts (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
        at Parser.pp$3.parseMaybeUnary (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
        at Parser.pp$3.parseExprOps (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
        at Parser.pp$3.parseMaybeConditional (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
        at Parser.pp$3.parseMaybeAssign (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
        at Parser.pp$3.parseExpression (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:1577:63)
        at Parser.pp$1.parseStatement (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
        at Parser.pp$1.parseLabeledStatement (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:958:22)
        at Parser.pp$1.parseStatement (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:729:21)
        at Parser.pp$1.parseBlock (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
        at Parser.pp$1.parseStatement (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
        at Parser.pp$1.parseTopLevel (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
        at Parser.parse (/Users/praveenkumar/Downloads/git/sunmool.client/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)

**Comment by oliviertassinari** [comment]
@praveen4554 Do you have a reproduction example?

**Comment by praveen4554** [comment]
If you want I can provide web pack configuration

**Comment by woutervanvliet** [comment]
@praveen4554 If you are still having this issue, then please do provide your webpack configuration. Or even better, a minimal repo that reproduces the problem.

**Comment by linonetwo** [comment]
I can reproduce it!
Try https://github.com/linonetwo/ipfs-browser-gateway/tree/serviceworker-webpack-plugin

**Comment by linonetwo** [comment]
That was my fault. I delete babel plugin that was placed before this plugin by mistake. Restore babel plugin then there is no this error.

**Comment by woutervanvliet** [comment]
So it is solved? Closing the issue.

**Comment by praveen4554** [comment]
The servicer worker plugin I am integrating with angular4 web pack still it is not working
