### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by Hallya** [oliviertassinari/serviceworker-webpack-plugin#70]
Hi,

I'm trying run my webpack config but it seems that your plugins is using an old version and is now deprecated. 

Here's the deprecation trace from my console:

```
npm run build

> mws-restaurant-stage-1@1.0.0 build /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1
> webpack --mode production

(node:58909) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at ServiceWorkerPlugin.apply (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/serviceworker-webpack-plugin/lib/index.js:84:16)
    at webpack (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:436:16)
    at yargs.parse (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Object.parse (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:514:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/bin/webpack.js:80:2)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
(node:58909) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
    at ServiceWorkerPlugin.handleMake (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/serviceworker-webpack-plugin/lib/index.js:122:21)
    at /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/serviceworker-webpack-plugin/lib/index.js:104:15
    at AsyncParallelHook.eval [as callAsync] (eval at create (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:13:1)
    at AsyncParallelHook.lazyCompileHook [as _callAsync] (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.beforeCompile.callAsync.err (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:476:20)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:469:28)
    at readRecords.err (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:220:11)
    at Compiler.readRecords (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:342:11)
    at hooks.run.callAsync.err (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:217:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.beforeRun.callAsync.err (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:214:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.run (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:211:24)
    at processOptions (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:509:20)
    at yargs.parse (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Object.parse (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:514:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/bin/webpack.js:80:2)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
Error: Something went wrong during the make event.
    at /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/serviceworker-webpack-plugin/lib/index.js:107:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mws-restaurant-stage-1@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mws-restaurant-stage-1@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by devCrossNet** [comment]
Hey, can you install version: 1.0.0-alpha02 and see if it solves your problem?

**Comment by Hallya** [comment]
Sure, how do you do that ?

**Comment by devCrossNet** [comment]
`npm install --save serviceworker-webpack-plugin@1.0.0-alpha02` or `npm install --save serviceworker-webpack-plugin@next`

**Comment by Hallya** [comment]
I'm getting this:
```
npm run build

> mws-restaurant-stage-1@1.0.0 build /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1
> webpack --mode production

Error: Something went wrong during the make event.
    at /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/serviceworker-webpack-plugin/lib/index.js:109:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mws-restaurant-stage-1@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mws-restaurant-stage-1@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dulac/.npm/_logs/2018-04-23T12_36_27_218Z-debug.log
```

**Comment by devCrossNet** [comment]
never got this error. I am currently at version `1.0.0-alpha01` maybe you try this instead

**Comment by Hallya** [comment]
It's doing almost the same as the first time: 
```
npm run build

> mws-restaurant-stage-1@1.0.0 build /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1
> webpack --mode production

(node:59507) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
    at ServiceWorkerPlugin.handleMake (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/serviceworker-webpack-plugin/lib/index.js:124:21)
    at /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/serviceworker-webpack-plugin/lib/index.js:106:15
    at AsyncParallelHook.eval [as callAsync] (eval at create (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:13:1)
    at AsyncParallelHook.lazyCompileHook [as _callAsync] (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.beforeCompile.callAsync.err (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:476:20)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:469:28)
    at readRecords.err (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:220:11)
    at Compiler.readRecords (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:342:11)
    at hooks.run.callAsync.err (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:217:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.beforeRun.callAsync.err (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:214:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.run (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/Compiler.js:211:24)
    at processOptions (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:509:20)
    at yargs.parse (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Object.parse (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:514:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/bin/webpack.js:80:2)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
Error: Something went wrong during the make event.
    at /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/serviceworker-webpack-plugin/lib/index.js:109:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mws-restaurant-stage-1@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mws-restaurant-stage-1@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dulac/.npm/_logs/2018-04-23T12_41_57_769Z-debug.log
```
Do you want to have a look to my webpack config, the sw.js or the main.js that register to the service worker ?

**Comment by devCrossNet** [comment]
you can have a look at my working example here: https://github.com/devCrossNet/vue-starter and here https://github.com/devCrossNet/vue-starter/blob/master/config/webpack.client.config.js#L45

but I think this issue is not related to a configuration mistake :-/

**Comment by Hallya** [comment]
Thanks, I'm looking into it right now !

**Comment by Hallya** [comment]
Hi again, you have the same problem than me:
```
npm run build:client

> vue-starter@0.0.0 build:client /Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter
> cross-env NODE_ENV=production webpack --mode production --config ./config/webpack.client.config.js

(node:61224) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
    at ServiceWorkerPlugin.handleMake (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/serviceworker-webpack-plugin/lib/index.js:124:21)
    at /Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/serviceworker-webpack-plugin/lib/index.js:106:15
    at AsyncParallelHook.eval [as callAsync] (eval at create (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:25:1)
    at AsyncParallelHook.lazyCompileHook [as _callAsync] (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.beforeCompile.callAsync.err (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/webpack/lib/Compiler.js:476:20)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/webpack/lib/Compiler.js:469:28)
    at readRecords.err (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/webpack/lib/Compiler.js:220:11)
    at Compiler.readRecords (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/webpack/lib/Compiler.js:342:11)
    at hooks.run.callAsync.err (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/webpack/lib/Compiler.js:217:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.beforeRun.callAsync.err (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/webpack/lib/Compiler.js:214:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.run (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/webpack/lib/Compiler.js:211:24)
    at processOptions (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/webpack-cli/bin/webpack.js:509:20)
    at yargs.parse (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Object.parse (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/webpack-cli/bin/webpack.js:514:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/dulac/Desktop/CloudStation/WebWork/Hallya/vue-starter/node_modules/webpack/bin/webpack.js:80:2)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
```

**Comment by devCrossNet** [comment]
this must be a new one. it was fine yesterday. will have a look asap.

**Comment by Hallya** [comment]
Works with 1.0.0-alpha02

**Comment by Hallya** [comment]
I think I've made a mistake. Because I saw `Entrypoint undefined = sw.js` I've modified the `entry` the way webpack do for multiple entries:
```
plugins: [
    new ServiceWorkerWebpackPlugin({
      entry: {
        ServiceWorker: path.join(__dirname, 'dev/sw.js')
      }
    })
  ]
```
Now it is like you did in your project:
```
plugins: [
    new ServiceWorkerWebpackPlugin({
      entry: path.join(__dirname, 'dev/sw.js')
    })
  ]
```
And I get:
```
npm run build

> mws-restaurant-stage-1@1.0.0 build /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1
> webpack --mode production

Hash: e367ac49c6b658ba382f
Version: webpack 4.6.0
Time: 821ms
Built at: 2018-04-23 15:09:06
 3 assets
Entrypoint main = main.js
Entrypoint restaurant = restaurant.js
[0] ./dev/js/restaurant_info.js 8.46 KiB {0} [built]
[2] ./dev/js/main.js 15.3 KiB {1} [built]
    + 1 hidden module
Child serviceworker-plugin:
     1 asset
    Entrypoint undefined = sw.js
    [0] ./dev/sw.js 4.62 KiB {0} [built]

    ERROR in ./dev/sw.js
    Module not found: Error: Can't resolve 'js/indexedb' in '/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/dev'
     @ ./dev/sw.js 3:16-38
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mws-restaurant-stage-1@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mws-restaurant-stage-1@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dulac/.npm/_logs/2018-04-23T13_09_06_070Z-debug.log
```
I was thinking it was weird to have an Entrypoint undefined so I modified it. Sorry for loosing your time on this ! 
Still, you got a problem with webpack 😄 .

Anyway, do you have an idea on how to solve my issue ? I'm just trying to integrate webpack in my project but I'm struggling.

**Comment by mouhsinelonly** [comment]
i have a similar issue after upgrading to v4

Entrypoint undefined = service-worker.js



in config :

entry: path.join(__dirname, '../src/service-worker.js')
